import { Link, useNavigate } from "react-router-dom";
import { useResponsive } from '../../config/responsive';
import BackButton from '../../components/ui/BackButton';
const TermsConditionPage = () =>{
	const { isDesktopOrLaptop, isTabletOrMobile } = useResponsive();
	const navigate = useNavigate();
    return(
        <>
        <section className="main_container main_container_new">
		    <div className="container">
			{isDesktopOrLaptop && (
				<BackButton/>
			)}
				<div className="card big_card textonly">
			        <h1 className="txt-primary fs-4">Terms & conditions</h1>
			        <div className="mt-5">
  <p>
    This document sets out the Terms of Use ("Terms") under which Students, Visitors, Users, Educational Institutions, Corporate Bodies (collectively, “Users,” “you,” or “your”) may access and use the website <strong>www.deijobs.in</strong> (“Site”), operated by <strong>DEIJobs</strong> ("we," "us," or "our").
  </p>
  <p>
    This electronic document is a valid legal record under the Information Technology Act, 2000, and applicable rules and amendments. It is generated by a computer system and does not require physical or digital signatures. The Terms comply with the Information Technology (Intermediaries Guidelines) Rules, 2011, which require publishing rules, privacy policies, and user agreements.
  </p>
  <p>
    We reserve the right to modify these Terms at any time without prior notice. You should review these Terms periodically to stay informed of updates. Continued use of the Site after changes implies acceptance of the updated Terms. The effective date of the latest revision will be indicated as the "Last Revised Date."
  </p>
  <p>
    By accessing or using the Site, you agree to these Terms and any future amendments. If you register on the Site, you confirm that you are at least 18 years old and legally competent to enter into this agreement. If you accept these Terms on behalf of an organization or minor, you warrant you have authority to do so, and they will be bound by these Terms.
  </p>
  <p>Please review our <strong>Privacy Policy</strong> for details on how we collect, use, and protect your information.</p>

  <h2>1. Overview of Our Services</h2>
  <p>
    DEIJobs is an online platform that allows Users to upload resumes and search for job opportunities across various organizations in India and abroad. Corporate Bodies can post job vacancies, search for candidates, and use value-added services such as showcasing their profiles, CSR activities, testimonials, and more. All use of the Site is subject to these Terms and any posted guidelines or rules.
  </p>

  <h2>2. Changes to Terms</h2>
  <p>
    We may update or modify these Terms at our discretion. Please check this page regularly. Your continued use after changes means you accept them. Additional terms may apply for services provided through partners.
  </p>

  <h2>3. Site Availability</h2>
  <p>
    Site features and services may change or be discontinued at any time without notice. We do not guarantee updates to content or availability.
  </p>

  <h2>4. Eligibility</h2>
  <p>
    You represent that all information you provide is truthful, current, and accurate. You agree your use complies with applicable laws and that you are at least 18 years old or have parental consent if underage. We may suspend or terminate your access at any time.
  </p>

  <h2>5. Registration</h2>
  <p>
    To upload resumes or post jobs, Users and Corporate Bodies must register with accurate information and keep it updated. We reserve the right to refuse or terminate accounts without notice for any reason. You are responsible for maintaining the confidentiality of your login credentials and for all activity on your account. Multiple accounts per User are not allowed.
  </p>

  <h2>6. Services for Users</h2>
  <ul>
    <li>Users may upload and manage their profiles and resumes.</li>
    <li>We reserve the right to reject or modify profiles or content to fit our database.</li>
    <li>Users may not upload resumes or information belonging to others.</li>
    <li>We do not guarantee responses to profiles or suitability of job listings.</li>
    <li>Users access job postings at their own risk; we do not verify employers or job details.</li>
  </ul>

  <h2>7. Services for Corporate Bodies</h2>
  <ul>
    <li>Registered Corporate Bodies can post profiles, job openings, and related information.</li>
    <li>They must ensure accuracy of their postings; we are not liable for errors.</li>
    <li>We may edit postings for typographical or formatting reasons.</li>
    <li>Access and posting limits depend on the subscription package purchased.</li>
    <li>We reserve the right to reject or remove postings without explanation.</li>
    <li>Corporate Bodies are responsible for verifying applicant information independently.</li>
    <li>We do not guarantee responses or job posting effectiveness.</li>
    <li>Corporate Bodies confirm all job postings are genuine and authorized.</li>
    <li>Confidential data not intended for public display will be treated as such.</li>
    <li>Access to services may be suspended for non-payment or contract termination.</li>
  </ul>

  <h2>8. User Representations</h2>
  <p>
    By registering, Users confirm they are 18+ and that all information provided is accurate. Use of the Site and reliance on its content is at the User’s sole risk.
  </p>

  <h2>9. Corporate Body Representations</h2>
  <p>
    Corporate Bodies warrant they are duly registered entities or individuals with legal authority to post jobs and that provided information is truthful and accurate. They affirm no legal or criminal proceedings affect their eligibility and that they are not blacklisted by any authority.
  </p>

  <h2>10. Payments & Consideration</h2>
  <p>
    Corporate Bodies pay fees for services as per their agreements with DEIJobs.
  </p>

  <h2>11. Cancellation and Refunds</h2>
  <ul>
    <li>Setup and annual fees are non-refundable.</li>
    <li>No refunds or cancellations for monthly or quarterly subscriptions.</li>
    <li>Annual subscriptions may be canceled after 6 months; unused periods may be frozen for future use, but no cash refunds are given.</li>
  </ul>

  <h2>12. Reviews and Ratings</h2>
  <ul>
    <li>Users may post reviews or ratings of Corporate Bodies and job postings, assuming responsibility for their content.</li>
    <li>We may publish or remove any reviews at our discretion.</li>
    <li>Corporate Bodies may respond to reviews, subject to our moderation.</li>
  </ul>

  <h2>13. Prohibited Uses</h2>
  <p>You agree not to use the Site unlawfully or in ways that harm the Site or other Users, including but not limited to:</p>
  <ul>
    <li>Violating laws or regulations;</li>
    <li>Uploading harmful software or spam;</li>
    <li>Attempting unauthorized access;</li>
    <li>Misusing trademarks or intellectual property;</li>
    <li>Posting offensive, illegal, or false content.</li>
  </ul>

  <h2>14. Privacy Policy</h2>
  <p>Your use of the Site is subject to our Privacy Policy, which explains how we handle personal data.</p>

  <h2>15. Intellectual Property</h2>
  <p>
    All content, trademarks, and materials on the Site are owned or licensed by DEIJobs. Use of these without permission is prohibited.
  </p>

  <h2>16. Disclaimers and Limitation of Liability</h2>
  <p>
    The Site and services are provided "as is" without warranties. We do not guarantee accuracy, completeness, or uninterrupted access. Use of the Site is at your own risk. We disclaim implied warranties including merchantability and fitness for a particular purpose. We are not responsible for any damages resulting from your use of the Site.
  </p>

  <h2>17. Limitation of Liability</h2>
  <p>
    To the fullest extent permitted by law, DEIJobs and its affiliates shall not be liable to you or any third party for any damages of any kind, including direct, indirect, special, consequential, or exemplary damages, arising out of or related to your use or inability to use the Site or its content, or any linked third-party websites. This includes, but is not limited to, lost profits, business interruption, loss of data, delays, computer viruses, or network failures. By using the Site, you waive any rights to hold DEIJobs or its affiliates liable and agree not to participate in any class action suit related to damages or losses from your use of the Site.
  </p>

  <h2>18. Indemnification</h2>
  <p>
    You agree to indemnify, defend, and hold harmless DEIJobs and its affiliates from and against any claims, damages, liabilities, losses, or expenses (including reasonable attorney’s fees) arising from:
  </p>
  <ul>
    <li>Content or information you submit to the Site;</li>
    <li>Your breach of these Terms;</li>
    <li>Violation of any applicable laws or rights of others, including fraud or misrepresentation;</li>
    <li>Any breach of your warranties or representations under these Terms.</li>
  </ul>

  <h2>19. Partner Services</h2>
  <p>
    The Site may contain links to third-party websites or services for your convenience. We do not endorse or assume responsibility for the content, products, services, or practices of any linked sites. Your use of third-party sites is at your own risk and subject to their terms.
  </p>

  <h2>20. Violations and Termination</h2>
  <p>
    Your access and registration may be suspended or terminated if you violate any of these Terms or engage in misconduct as determined by DEIJobs at its sole discretion.
  </p>

  <h2>21. User Communications</h2>
  <p>
    By agreeing to these Terms, you consent to receive electronic communications from DEIJobs, including emails and notices posted on the Site. These communications fulfill any legal requirements for written notices.
  </p>

  <h2>22. Resolution of Disputes</h2>
  <p>
    These Terms are governed by the laws of Maharashtra, India, without regard to conflict of law principles. Any disputes arising from or relating to these Terms shall be subject to the exclusive jurisdiction of courts in Mumbai, Maharashtra, India. The Site is operated from India, and users accessing it do so at their own risk and responsibility for compliance with local laws. DEIJobs may restrict access to the Site by geographic region or other criteria at its sole discretion.
  </p>

  <h2>23. Notice</h2>
  <p>
    Unless otherwise stated, legal notices to you will be sent to the email address you provide during registration. Notices are deemed delivered 24 hours after sending unless delivery failure is reported. Alternatively, notices may be sent by mail to your registered address and will be deemed delivered three days after mailing.
  </p>

  <h2>24. Entire Agreement</h2>
  <p>
    This User Agreement, including all referenced documents, constitutes the entire agreement between you and DEIJobs regarding your use of the Site. For any questions or requests, please contact us at:
  </p>
  <p>Email: <a href="mailto:info@deijobs.in">info@deijobs.in</a></p>
</div>

		        </div>		
		    </div>
	    </section>

        </>
    )
}

export default TermsConditionPage;